backend:
  name: github
  branch: master # Branch to update (optional; defaults to master)
  auth_type: implicit
  repo: vjurj/RecipeManager
  app_id: Iv23ligbe25wYqlkkEuu
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "public/images" # Location where files will be stored in the repo
public_folder: "/images" # The src attribute for uploaded media