backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  repo: vjurj/RecipeManager
  auth_endpoint: /api/auth
site_url: https://vjurj.github.io/RecipeManager
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in frontmatter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Featured Image", name: "heroImage", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

media_folder: "src/content/images" # Location where files will be stored in the repo
public_folder: "/images" # The src attribute for uploaded media